import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'sr' | 'en' | 'ru' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('language');
      return (saved as Language) || 'sr';
    } catch {
      return 'sr';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('language', language);
    } catch {
      // Ignore localStorage errors
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback for development/HMR issues
    console.warn('useLanguage must be used within LanguageProvider - using fallback');
    return {
      language: 'sr' as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
}

// Translations
const translations: Record<Language, any> = {
  sr: {
    nav: {
      home: 'Početna',
      browse: 'Ponuda',
      about: 'O Nama',
      contact: 'Kontaktirajte Nas',
      lightTheme: 'Svetla Tema',
      darkTheme: 'Tamna Tema',
    },
    hero: {
      title: 'Pronađite Svoj Savršen Dom',
      subtitle: 'Premium nekretnine u Beogradu i okolini. Profesionalna usluga od početka do kraja.',
      forSale: 'Prodaja',
      forRent: 'Iznajmljivanje',
      viewListings: 'Pogledaj Ponudu',
      badge: 'Profesionalna Agencija za Nekretnine',
      headline: 'Vaš Partner u Pronalaženju',
      headlineAccent: 'Savršenog Doma',
      founded: 'Godina Osnivanja',
      completedDeals: 'Završenih Poslova',
      legalSupport: 'Pravna Podrška',
    },
    cta: {
      title: 'Pronađimo Zajedno Vaš Savršeni Dom',
      subtitle: 'Kontaktirajte nas danas i otkrijte kako možemo pomoći u ostvarivanju vaših želja za nekretninom.',
      browse: 'Pogledajte Ponudu',
    },
    featured: {
      title: 'Istaknute Nekretnine',
      viewAll: 'Pogledaj Sve',
      subtitle: 'Pogledajte naše najbolje trenutno dostupne nekretnine za prodaju i izdavanje',
    },
    stats: {
      title: 'Naši Rezultati',
      completed: 'Završenih Poslova',
      since: 'Poslujemo Od',
      support: 'Podrška 24/7',
      team: 'Advokatski Tim',
    },
    filters: {
      location: 'Lokacija',
      allLocations: 'Sve Lokacije',
      priceRange: 'Cena',
      allPrices: 'Sve Cene',
      area: 'Kvadratura',
      allAreas: 'Sve Kvadrature',
      type: 'Tip',
      allTypes: 'Svi tipovi',
      sale: 'Prodaja',
      rent: 'Iznajmljivanje',
      search: 'Pretraži',
    },
    listing: {
      perMonth: 'mesečno',
      bedrooms: 'Broj Soba',
      bathrooms: 'Kupatila',
      area: 'Površina',
      floor: 'Sprat',
      rooms: 'Sobe',
      heating: 'Grejanje',
      parking: 'Parking',
      renovated: 'Renoviran',
      orientation: 'Orijentacija',
      furniture: 'Nameštaj',
      distanceToRiver: 'Udaljenost od reke',
      description: 'O ovoj nekretnini',
      features: 'Karakteristike',
      location: 'Lokacija',
      details: 'Detalji',
      schedule: 'Zakažite Razgledanje',
      contact: 'Kontaktirajte Nas',
      viewDetails: 'Pogledaj Detalje',
      notFound: 'Nekretnina nije pronađena',
      backToBrowse: 'Nazad na ponudu',
      forSale: 'Prodaja',
      forRent: 'Izdavanje',
    },
    contact: {
      title: 'Kontakt Informacije',
      agent: 'Glavni Agent',
      phone: 'Telefon',
      email: 'Email',
      close: 'Zatvori',
    },
    schedule: {
      title: 'Zakažite Razgledanje',
      subtitle: 'Izaberite način kontakta',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'Email',
      whatsappDesc: 'Kontaktirajte nas preko WhatsApp-a',
      viberDesc: 'Pozovite nas preko Viber-a',
      emailDesc: 'Pošaljite nam email',
      close: 'Zatvori',
    },
    about: {
      title: 'O Nama',
      subtitle: 'Profesionalna agencija za nekretnine sa dugogodišnjim iskustvom',
      story: 'Naša Priča',
      storyText: 'Nekretnine Stepenik je osnovana 2021. godine sa vizijom da pruži vrhunsku uslugu u oblasti prometa nekretnina. Fokusirani smo na izgradnju dugoročnih odnosa sa našim klijentima, pružajući im podršku i stručnost u svakom koraku procesa kupovine ili iznajmljivanja nekretnina.',
      mission: 'Naša Misija',
      missionText: 'Pratimo naše klijente od početka do kraja svakog posla, osiguravajući da svaki detalj bude savršeno izvršen. Sa preko 150 uspešno završenih poslova u prodaji i izdavanju, izgradili smo reputaciju pouzdanog partnera u svetu nekretnina.',
      team: 'Naš Tim',
      teamText: 'Naš tim čine iskusni agenti za nekretnine i advokatski stručnjaci koji se brinu o svim pravnim aspektima transakcija. Ova kombinacija osigurava da naši klijenti dobiju kompletan i siguran servis.',
      whyUs: 'Zašto Nekretnine Stepenik?',
      experienced: 'Iskusan Tim',
      experiencedDesc: 'Dugogodišnje iskustvo u oblasti nekretnina',
      legal: 'Pravna Podrška',
      legalDesc: 'Advokatski tim koji se bavi pravnim aspektima',
      support: 'Kompletna Podrška',
      supportDesc: 'Pratimo vas od početka do kraja posla',
      trust: 'Pouzdanost',
      trustDesc: 'Preko 150 zadovoljnih klijenata',
    },
    footer: {
      description: 'Profesionalna agencija za nekretnine sa dugogodišnjim iskustvom u prodaji i iznajmljivanju stanova.',
      quickLinks: 'Brzi Linkovi',
      home: 'Početna',
      browse: 'Ponuda',
      about: 'O Nama',
      contact: 'Kontakt',
      contactInfo: 'Kontakt Informacije',
      phone: 'Telefon',
      email: 'Email',
      address: 'Adresa',
      addressText: 'Beograd, Srbija',
      rights: 'Sva prava zadržana.',
      services: 'Naše Usluge',
      buying: 'Kupovina Nekretnina',
      selling: 'Prodaja Nekretnina',
      renting: 'Iznajmljivanje',
      legal: 'Pravna Podrška',
    },
  },
  en: {
    nav: {
      home: 'Home',
      browse: 'Browse',
      about: 'About Us',
      contact: 'Contact Us',
      lightTheme: 'Light Theme',
      darkTheme: 'Dark Theme',
    },
    hero: {
      title: 'Find Your Perfect Home',
      subtitle: 'Premium real estate in Belgrade and surrounding areas. Professional service from start to finish.',
      forSale: 'For Sale',
      forRent: 'For Rent',
      viewListings: 'View Listings',
      badge: 'Professional Real Estate Agency',
      headline: 'Your Partner in Finding',
      headlineAccent: 'The Perfect Home',
      founded: 'Year Founded',
      completedDeals: 'Completed Deals',
      legalSupport: 'Legal Support',
    },
    cta: {
      title: 'Find Your Perfect Home Together',
      subtitle: 'Contact us today and discover how we can help you achieve your real estate goals.',
      browse: 'Browse Listings',
    },
    featured: {
      title: 'Featured Listings',
      viewAll: 'View All',
      subtitle: 'Check out our best currently available properties for sale and rent',
    },
    stats: {
      title: 'Our Results',
      completed: 'Completed Deals',
      since: 'Operating Since',
      support: '24/7 Support',
      team: 'Legal Team',
    },
    filters: {
      location: 'Location',
      allLocations: 'All Locations',
      priceRange: 'Price',
      allPrices: 'All Prices',
      area: 'Area',
      allAreas: 'All Areas',
      type: 'Type',
      allTypes: 'All Types',
      sale: 'For Sale',
      rent: 'For Rent',
      search: 'Search',
    },
    listing: {
      perMonth: 'per month',
      bedrooms: 'Bedrooms',
      bathrooms: 'Bathrooms',
      area: 'Area',
      floor: 'Floor',
      rooms: 'Rooms',
      heating: 'Heating',
      parking: 'Parking',
      renovated: 'Renovated',
      orientation: 'Orientation',
      furniture: 'Furniture',
      distanceToRiver: 'Distance to River',
      description: 'About this property',
      features: 'Features',
      location: 'Location',
      details: 'Details',
      schedule: 'Schedule Viewing',
      contact: 'Contact Us',
      viewDetails: 'View Details',
      notFound: 'Property not found',
      backToBrowse: 'Back to listings',
      forSale: 'For Sale',
      forRent: 'For Rent',
    },
    contact: {
      title: 'Contact Information',
      agent: 'Main Agent',
      phone: 'Phone',
      email: 'Email',
      close: 'Close',
    },
    schedule: {
      title: 'Schedule Viewing',
      subtitle: 'Choose contact method',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'Email',
      whatsappDesc: 'Contact us via WhatsApp',
      viberDesc: 'Call us via Viber',
      emailDesc: 'Send us an email',
      close: 'Close',
    },
    about: {
      title: 'About Us',
      subtitle: 'Professional real estate agency with years of experience',
      story: 'Our Story',
      storyText: 'Nekretnine Stepenik was founded in 2021 with a vision to provide premium service in real estate. We focus on building long-term relationships with our clients, providing support and expertise at every step of the buying or renting process.',
      mission: 'Our Mission',
      missionText: 'We follow our clients from start to finish in every deal, ensuring that every detail is perfectly executed. With over 150 successfully completed sales and rentals, we have built a reputation as a trusted partner in real estate.',
      team: 'Our Team',
      teamText: 'Our team consists of experienced real estate agents and legal professionals who handle all legal aspects of transactions. This combination ensures our clients receive complete and secure service.',
      whyUs: 'Why Nekretnine Stepenik?',
      experienced: 'Experienced Team',
      experiencedDesc: 'Years of experience in real estate',
      legal: 'Legal Support',
      legalDesc: 'Legal team handling legal aspects',
      support: 'Complete Support',
      supportDesc: 'We follow you from start to finish',
      trust: 'Reliability',
      trustDesc: 'Over 150 satisfied clients',
    },
    footer: {
      description: 'Professional real estate agency with years of experience in sales and rentals.',
      quickLinks: 'Quick Links',
      home: 'Home',
      browse: 'Browse',
      about: 'About',
      contact: 'Contact',
      contactInfo: 'Contact Information',
      phone: 'Phone',
      email: 'Email',
      address: 'Address',
      addressText: 'Belgrade, Serbia',
      rights: 'All rights reserved.',
      services: 'Our Services',
      buying: 'Real Estate Purchase',
      selling: 'Real Estate Sale',
      renting: 'Real Estate Rental',
      legal: 'Legal Support',
    },
  },
  ru: {
    nav: {
      home: 'Главная',
      browse: 'Предложения',
      about: 'О Нас',
      contact: 'Связаться',
      lightTheme: 'Светлая Тема',
      darkTheme: 'Темная Тема',
    },
    hero: {
      title: 'Найдите Свой Идеальный Дом',
      subtitle: 'Премиальная недвижимость в Белграде и окрестностях. Профессиональный сервис от начала до конца.',
      forSale: 'Продажа',
      forRent: 'Аренда',
      viewListings: 'Смотреть Объявления',
      badge: 'Профессиональное Агентство Недвижимости',
      headline: 'Ваш Партнер в Поиске',
      headlineAccent: 'Идеального Дома',
      founded: 'Год Основания',
      completedDeals: 'Завершенных Сделок',
      legalSupport: 'Юридическая Поддержка',
    },
    cta: {
      title: 'Найдем Ваш Идеальный Дом Вместе',
      subtitle: 'Свяжитесь с нами сегодня и узнайте, как мы можем помочь вам достичь ваших целей в недвижимости.',
      browse: 'Просмотреть Объявления',
    },
    featured: {
      title: 'Рекомендуемые Объявления',
      viewAll: 'Показать Все',
      subtitle: 'Посмотрите наши лучшие в данный момент доступные недвижимости для продажи и аренды',
    },
    stats: {
      title: 'Наши Результаты',
      completed: 'Завершенных Сделок',
      since: 'Работаем С',
      support: 'Поддержка 24/7',
      team: 'Юридическая Команда',
    },
    filters: {
      location: 'Местоположение',
      allLocations: 'Все Локации',
      priceRange: 'Цена',
      allPrices: 'Все Цены',
      area: 'Площадь',
      allAreas: 'Все Площади',
      type: 'Тип',
      allTypes: 'Все типы',
      sale: 'Продажа',
      rent: 'Аренда',
      search: 'Поиск',
    },
    listing: {
      perMonth: 'в месяц',
      bedrooms: 'Спальни',
      bathrooms: 'Ванные',
      area: 'Площадь',
      floor: 'Этаж',
      rooms: 'Комнаты',
      heating: 'Отопление',
      parking: 'Парковка',
      renovated: 'Отремонтирован',
      orientation: 'Ориентация',
      furniture: 'Мебель',
      distanceToRiver: 'Расстояние до реки',
      description: 'Описание',
      features: 'Характеристики',
      location: 'Местоположение',
      details: 'Детали',
      schedule: 'Запланировать Просмотр',
      contact: 'Связаться',
      viewDetails: 'Подробнее',
      notFound: 'Недвижимость не найдена',
      backToBrowse: 'Назад к объявлениям',
      forSale: 'Продажа',
      forRent: 'Аренда',
    },
    contact: {
      title: 'Контактная Информация',
      agent: 'Главный Агент',
      phone: 'Телефон',
      email: 'Email',
      close: 'Закрыть',
    },
    schedule: {
      title: 'Запланировать Просмотр',
      subtitle: 'Выберите способ связи',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'Email',
      whatsappDesc: 'Свяжитесь с нами через WhatsApp',
      viberDesc: 'Позвоните нам через Viber',
      emailDesc: 'Отправьте нам email',
      close: 'Закрыть',
    },
    about: {
      title: 'О Нас',
      subtitle: 'Профессиональное агентство недвижимости с многолетним опытом',
      story: 'Наша История',
      storyText: 'Nekretnine Stepenik была основана в 2021 году с видением предоставления премиального сервиса в сфере недвижимости. Мы фокусируемся на построении долгосрочных отношений с нашими клиентами, предоставляя поддержку и экспертизу на каждом этапе покупки или аренды недвижимости.',
      mission: 'Наша Миссия',
      missionText: 'Мы сопровождаем наших клиентов от начала до конца каждой сделки, гарантируя идеальное выполнение каждой детали. Более 150 успешно завершенных продаж и сдач в аренду создали нам репутацию надежного партнера в сфере недвижимости.',
      team: 'Наша Команда',
      teamText: 'Наша команда состоит из опытных агентов по недвижимости и юридических специалистов, которые занимаются всеми правовыми аспектами сделок. Эта комбинация гарантирует нашим клиентам полный и безопасный сервис.',
      whyUs: 'Почему Nekretnine Stepenik?',
      experienced: 'Опытная Команда',
      experiencedDesc: 'Многолетний опыт в сфере недвижимости',
      legal: 'Юридическая Поддержка',
      legalDesc: 'Юридическая команда занимается правовыми а��пектами',
      support: 'Полная Поддержка',
      supportDesc: 'Мы сопровождаем вас от начала до конца',
      trust: 'Надежность',
      trustDesc: 'Более 150 довольных клиентов',
    },
    footer: {
      description: 'Профессиональное агентство недвижимости с многолетним опытом продаж и аренды.',
      quickLinks: 'Быстрые Ссылки',
      home: 'Главная',
      browse: 'Предложения',
      about: 'О Нас',
      contact: 'Контакт',
      contactInfo: 'Контактная Информация',
      phone: 'Телефон',
      email: 'Email',
      address: 'Адрес',
      addressText: 'Белград, Сербия',
      rights: 'Все права защищены.',
      services: 'Наши Услуги',
      buying: 'Покупка Недвижимости',
      selling: 'Продажа Недвижимости',
      renting: 'Аренда Недвижимости',
      legal: 'Юридическая Поддержка',
    },
  },
  tr: {
    nav: {
      home: 'Ana Sayfa',
      browse: 'İlanlar',
      about: 'Hakkımızda',
      contact: 'İletişim',
      lightTheme: 'Açık Tema',
      darkTheme: 'Koyu Tema',
    },
    hero: {
      title: 'Mükemmel Evinizi Bulun',
      subtitle: 'Belgrad ve çevresinde premium gayrimenkul. Baştan sona profesyonel hizmet.',
      forSale: 'Satılık',
      forRent: 'Kiralık',
      viewListings: 'İlanları Görüntüle',
      badge: 'Profesyonel Gayrimenkul Ajansı',
      headline: 'Mükemmel Ev Bulma İşte',
      headlineAccent: 'Parteriniz',
      founded: 'Kuruluş Yılı',
      completedDeals: 'Tamamlanan İşlemler',
      legalSupport: 'Yasal Destek',
    },
    cta: {
      title: 'Mükemmel Evimizi Birlikte Bulalım',
      subtitle: 'Bize bugün ulaşın ve gayrimenkul hedeflerinizi nasıl gerçekleştirebileceğimizi keşfedin.',
      browse: 'İlanları Göster',
    },
    featured: {
      title: 'Öne Çıkan İlanlar',
      viewAll: 'Tümünü Görüntüle',
      subtitle: 'Satış ve kiralık için şu anda mevcut en iyi gayrimenkulleri görün',
    },
    stats: {
      title: 'Sonuçlarımız',
      completed: 'Tamamlanan İşlemler',
      since: 'Hizmet Başlangıcı',
      support: '7/24 Destek',
      team: 'Hukuk Ekibi',
    },
    filters: {
      location: 'Konum',
      allLocations: 'Tüm Konumlar',
      priceRange: 'Fiyat',
      allPrices: 'Tüm Fiyatlar',
      area: 'Alan',
      allAreas: 'Tüm Alanlar',
      type: 'Tip',
      allTypes: 'Tüm Tipler',
      sale: 'Satılık',
      rent: 'Kiralık',
      search: 'Ara',
    },
    listing: {
      perMonth: 'aylık',
      bedrooms: 'Yatak Odası',
      bathrooms: 'Banyo',
      area: 'Alan',
      floor: 'Kat',
      rooms: 'Odalar',
      heating: 'Isıtma',
      parking: 'Park Yeri',
      renovated: 'Yenilenmiş',
      orientation: 'Yönelim',
      furniture: 'Mobilya',
      distanceToRiver: 'Nehre Mesafe',
      description: 'Açıklama',
      features: 'Özellikler',
      location: 'Konum',
      details: 'Detaylar',
      schedule: 'Görüntüleme Planla',
      contact: 'İletişime Geç',
      viewDetails: 'Detayları Görüntüle',
      notFound: 'Gayrimenkul bulunamadı',
      backToBrowse: 'İlanlara geri dön',
      forSale: 'Satılık',
      forRent: 'Kiralık',
    },
    contact: {
      title: 'İletişim Bilgileri',
      agent: 'Ana Temsilci',
      phone: 'Telefon',
      email: 'E-posta',
      close: 'Kapat',
    },
    schedule: {
      title: 'Görüntüleme Planla',
      subtitle: 'İletişim yöntemini seçin',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'E-posta',
      whatsappDesc: 'WhatsApp üzerinden iletişime geçin',
      viberDesc: 'Viber üzerinden arayın',
      emailDesc: 'Bize e-posta gönderin',
      close: 'Kapat',
    },
    about: {
      title: 'Hakkımızda',
      subtitle: 'Yıllarca deneyime sahip profesyonel gayrimenkul ajansı',
      story: 'Hikayemiz',
      storyText: 'Nekretnine Stepenik, 2021 yılında gayrimenkul alanında premium hizmet sunma vizyonuyla kuruldu. Müşterilerimizle uzun vadeli ilişkiler kurmaya odaklanıyor, satın alma veya kiralama sürecinin her adımında destek ve uzmanlık sağlıyoruz.',
      mission: 'Misyonumuz',
      missionText: 'Her işte müşterilerimizi baştan sona takip ediyor, her detayın mükemmel şekilde yürütülmesini sağlıyoruz. 150\'den fazla başarıyla tamamlanmış satış ve kiralamayla, gayrimenkul dünyasında güvenilir bir ortak olarak itibar kazandık.',
      team: 'Ekibimiz',
      teamText: 'Ekibimiz, işlemlerin tüm yasal yönlerini ele alan deneyimli gayrimenkul acenteleri ve hukuk uzmanlarından oluşmaktadır. Bu kombinasyon, müşterilerimizin eksiksiz ve güvenli hizmet almasını sağlar.',
      whyUs: 'Neden Nekretnine Stepenik?',
      experienced: 'Deneyimli Ekip',
      experiencedDesc: 'Gayrimenkul alanında yıllarca deneyim',
      legal: 'Hukuki Destek',
      legalDesc: 'Yasal konularla ilgilenen hukuk ekibi',
      support: 'Tam Destek',
      supportDesc: 'Baştan sona sizinle beraberiz',
      trust: 'Güvenilirlik',
      trustDesc: '150\'den fazla memnun müşteri',
    },
    footer: {
      description: 'Satış ve kiralamada yıllarca deneyime sahip profesyonel gayrimenkul ajansı.',
      quickLinks: 'Hızlı Bağlantılar',
      home: 'Ana Sayfa',
      browse: 'İlanlar',
      about: 'Hakkımızda',
      contact: 'İletişim',
      contactInfo: 'İletişim Bilgileri',
      phone: 'Telefon',
      email: 'E-posta',
      address: 'Adres',
      addressText: 'Belgrad, Sırbistan',
      rights: 'Tüm hakları saklıdır.',
      services: 'Hizmetlerimiz',
      buying: 'Gayrimenkul Satın Alma',
      selling: 'Gayrimenkul Satış',
      renting: 'Gayrimenkul Kiralama',
      legal: 'Hukuki Destek',
    },
  },
};