import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'sr' | 'en' | 'ru' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('language');
      return (saved as Language) || 'sr';
    } catch {
      return 'sr';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('language', language);
    } catch {
      // Ignore localStorage errors
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback for development/HMR issues - don't show warning in production
    if (process.env.NODE_ENV === 'development') {
      console.warn('useLanguage must be used within LanguageProvider - using fallback');
    }
    return {
      language: 'sr' as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
}

// Translations
const translations: Record<Language, any> = {
  sr: {
    nav: {
      home: 'Početna',
      browse: 'Ponuda',
      about: 'O Nama',
      contact: 'Kontaktirajte nas',
      buying: 'Kupujem',
      selling: 'Prodajem',
      lightTheme: 'Svetla Tema',
      darkTheme: 'Tamna Tema',
    },
    hero: {
      title: 'Pronađite Svoj Savršen Dom',
      subtitle: 'Nekretnine nisu skok, već promišljen uspon. Svaka odluka počinje prvim stepenikom.',
      forSale: 'Prodaja',
      forRent: 'Iznajmljivanje',
      viewListings: 'Pogledaj ponudu',
      badge: 'Agencija za nekretnine Stepenik',
      headline: 'Pravi stepenik između ponude',
      headlineAccent: 'i promišljene odluke',
      founded: 'Godina Osnivanja',
      completedDeals: 'Završenih Poslova',
      legalSupport: 'Zadovoljnih Klijenata',
      buying: 'Kupujem',
      selling: 'Prodajem',
    },
    cta: {
      title: 'Pronađimo zajedno vaš savršeni dom',
      subtitle: 'Kontaktirajte nas danas i otkrijte kako možemo pomoći u ostvarivanju vaših želja za nekretninom.',
      browse: 'Pogledajte Ponudu',
      contact: 'Kontaktirajte nas',
      buying: 'Kupujem',
      selling: 'Prodajem',
    },
    buying: {
      title: 'Kupujem Nekretninu',
      subtitle: 'Opišite nam kakvu nekretninu tražite i mi ćemo pronaći savršeno rešenje za vas',
      personalInfo: 'Vaši Podaci',
      name: 'Ime i Prezime',
      phone: 'Telefon',
      email: 'Email',
      namePlaceholder: 'Vaše ime',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'vas.email@primer.com',
      searchingFor: 'Šta Tražite?',
      propertyType: 'Tip Nekretnine',
      location: 'Lokacija',
      budget: 'Budžet',
      rooms: 'Broj Soba',
      additionalInfo: 'Dodatne Informacije',
      selectType: 'Izaberite tip',
      apartment: 'Stan',
      house: 'Kuća',
      commercial: 'Poslovni prostor',
      land: 'Plac',
      garage: 'Garaža',
      locationPlaceholder: 'Npr. Novi Beograd, Vračar...',
      budgetPlaceholder: 'Npr. do 100,000€',
      roomsPlaceholder: 'Npr. 2.0, 3.0...',
      messagePlaceholder: 'Opišite detaljnije šta tražite, posebne zahteve, preferirano orijentaciju, sprat, itd...',
      sendVia: 'Odaberite način slanja:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'Email',
      required: '* Obavezna polja',
      whyUs: 'Zašto Nekretnine Stepenik?',
      completedDeals: 'Završenih Poslova',
      legalSupport: 'Pravna Podrška',
      clientSupport: 'Podrška Klijentima',
    },
    selling: {
      title: 'Prodajem Nekretninu',
      subtitle: 'Opišite nam vašu nekretninu i mi ćemo je brzo prodati po najboljoj ceni',
      personalInfo: 'Vaši Podaci',
      name: 'Ime i Prezime',
      phone: 'Telefon',
      email: 'Email',
      namePlaceholder: 'Vaše ime',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'vas.email@primer.com',
      propertyDetails: 'Detalji Nekretnine',
      propertyType: 'Tip Nekretnine',
      location: 'Lokacija',
      squareMeters: 'Površina (m²)',
      floor: 'Sprat',
      rooms: 'Broj Soba',
      price: 'Cena',
      additionalInfo: 'Dodatne Informacije',
      selectType: 'Izaberite tip',
      apartment: 'Stan',
      house: 'Kuća',
      commercial: 'Poslovni prostor',
      land: 'Plac',
      garage: 'Garaža',
      locationPlaceholder: 'Npr. Novi Beograd, Vračar...',
      squareMetersPlaceholder: 'Npr. 65 m²',
      floorPlaceholder: 'Npr. 3/5',
      roomsPlaceholder: 'Npr. 2.0, 3.0...',
      pricePlaceholder: 'Npr. 120,000€',
      messagePlaceholder: 'Opišite stanje nekretnine, dodatne pogodnosti, renovacije, parking, terasu, itd...',
      sendVia: 'Odaberite način slanja:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'Email',
      required: '* Obavezna polja',
      advantages: 'Prednosti Prodaje Preko Nas',
      fastSale: 'Brza',
      fastSaleText: 'Prodaja',
      bestPrice: 'Najbolja',
      bestPriceText: 'Cena',
      legalSafety: 'Pravna',
      legalSafetyText: 'Sigurnost',
    },
    featured: {
      title: 'Istaknute Nekretnine',
      viewAll: 'Pogledaj Sve',
      subtitle: 'Pogledajte naše najbolje trenutno dostupne nekretnine za prodaju i izdavanje',
    },
    card: {
      forSale: 'Prodaja',
      forRent: 'Iznajmljivanje',
      month: 'mesečno',
    },
    stats: {
      title: 'Naši Rezultati',
      completed: 'Završenih Poslova',
      since: 'Poslujemo Od',
      support: 'Podrška 24/7',
      team: 'Advokatski Tim',
    },
    filters: {
      location: 'Lokacija',
      allLocations: 'Sve Lokacije',
      priceRange: 'Cena',
      allPrices: 'Sve Cene',
      area: 'Kvadratura',
      allAreas: 'Sve Kvadrature',
      type: 'Tip',
      allTypes: 'Svi tipovi',
      sale: 'Prodaja',
      rent: 'Iznajmljivanje',
      search: 'Pretraži',
    },
    listing: {
      perMonth: 'mesečno',
      bedrooms: 'Broj Soba',
      bathrooms: 'Kupatila',
      area: 'Površina',
      floor: 'Sprat',
      rooms: 'Sobe',
      heating: 'Grejanje',
      parking: 'Parking',
      renovated: 'Renoviran',
      orientation: 'Orijentacija',
      furniture: 'Nameštaj',
      distanceToRiver: 'Udaljenost od reke',
      description: 'O ovoj nekretnini',
      features: 'Karakteristike',
      location: 'Lokacija',
      details: 'Detalji',
      schedule: 'Zakažite Razgledanje',
      contact: 'Kontaktirajte Nas',
      viewDetails: 'Pogledaj Detalje',
      notFound: 'Nekretnina nije pronađena',
      backToBrowse: 'Nazad na ponudu',
      forSale: 'Prodaja',
      forRent: 'Izdavanje',
    },
    contact: {
      title: 'Kontakt Informacije',
      agent: 'Glavni Agent',
      phone: 'Telefon',
      email: 'Email',
      close: 'Zatvori',
    },
    schedule: {
      title: 'Zakažite Razgledanje',
      subtitle: 'Izaberite način kontakta',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'Email',
      whatsappDesc: 'Kontaktirajte nas preko WhatsApp-a',
      viberDesc: 'Pozovite nas preko Viber-a',
      emailDesc: 'Pošaljite nam email',
      close: 'Zatvori',
    },
    about: {
      title: 'O Nama',
      subtitle: 'Profesionalna agencija za nekretnine sa dugogodišnjim iskustvom',
      story: 'Naša Priča',
      storyText: 'Nekretnine Stepenik je osnovana 2021. godine sa vizijom da pruži vrhunsku uslugu u oblasti prometa nekretnina. Fokusirani smo na izgradnju dugoročnih odnosa sa našim klijentima, pružajući im podršku i stručnost u svakom koraku procesa kupovine ili iznajmljivanja nekretnina.',
      mission: 'Naša Misija',
      missionText: 'Pratimo naše klijente od početka do kraja svakog posla, osiguravajući da svaki detalj bude savršeno izvršen. Sa preko 150 uspešno završenih poslova u prodaji i izdavanju, izgradili smo reputaciju pouzdanog partnera u svetu nekretnina.',
      team: 'Naš Tim',
      teamText: 'Naš tim čine iskusni agenti za nekretnine i advokatski stručnjaci koji se brinu o svim pravnim aspektima transakcija. Ova kombinacija osigurava da naši klijenti dobiju kompletan i siguran servis.',
      whyUs: 'Zašto Nekretnine Stepenik?',
      experienced: 'Iskusan Tim',
      experiencedDesc: 'Dugogodišnje iskustvo u oblasti nekretnina',
      legal: 'Pravna Podrška',
      legalDesc: 'Advokatski tim koji se bavi pravnim aspektima',
      support: 'Kompletna Podrška',
      supportDesc: 'Pratimo vas od početka do kraja posla',
      trust: 'Pouzdanost',
      trustDesc: 'Preko 150 zadovoljnih klijenata',
    },
    footer: {
      description: 'Profesionalna agencija za nekretnine sa dugogodišnjim iskustvom u prodaji i iznajmljivanju stanova.',
      quickLinks: 'Brzi Linkovi',
      home: 'Početna',
      browse: 'Ponuda',
      about: 'O Nama',
      contact: 'Kontakt',
      contactInfo: 'Kontakt Informacije',
      phone: 'Telefon',
      email: 'Email',
      address: 'Adresa',
      addressText: 'Beograd, Srbija',
      rights: 'Sva prava zadržana.',
      services: 'Naše Usluge',
      buying: 'Kupovina Nekretnina',
      selling: 'Prodaja Nekretnina',
      renting: 'Iznajmljivanje',
      legal: 'Pravna Podrška',
    },
  },
  en: {
    nav: {
      home: 'Home',
      browse: 'Browse',
      about: 'About Us',
      contact: 'Contact us',
      buying: 'Buying',
      selling: 'Selling',
      lightTheme: 'Light Theme',
      darkTheme: 'Dark Theme',
    },
    hero: {
      title: 'Find Your Perfect Home',
      subtitle: 'Real estate is not a leap, but a well-thought-out ascent. Every decision starts with the first step.',
      forSale: 'For Sale',
      forRent: 'For Rent',
      viewListings: 'View listings',
      badge: 'Stepenik Real Estate Agency',
      headline: 'The right step between offer',
      headlineAccent: 'and thoughtful decision',
      founded: 'Year Founded',
      completedDeals: 'Completed Deals',
      legalSupport: 'Satisfied Clients',
      buying: 'Buying',
      selling: 'Selling',
    },
    cta: {
      title: 'Let\'s Find Your Perfect Home Together',
      subtitle: 'Contact us today and discover how we can help you achieve your real estate goals.',
      browse: 'Browse Listings',
      contact: 'Contact us',
      buying: 'Buying',
      selling: 'Selling',
    },
    buying: {
      title: 'Buying Property',
      subtitle: 'Describe to us what property you are looking for and we will find the perfect solution for you',
      personalInfo: 'Your Information',
      name: 'Full Name',
      phone: 'Phone',
      email: 'Email',
      namePlaceholder: 'Your name',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'your.email@example.com',
      searchingFor: 'What Are You Looking For?',
      propertyType: 'Property Type',
      location: 'Location',
      budget: 'Budget',
      rooms: 'Number of Rooms',
      additionalInfo: 'Additional Information',
      selectType: 'Select type',
      apartment: 'Apartment',
      house: 'House',
      commercial: 'Commercial property',
      land: 'Land',
      garage: 'Garage',
      locationPlaceholder: 'E.g. New Belgrade, Vračar...',
      budgetPlaceholder: 'E.g. up to €100,000',
      roomsPlaceholder: 'E.g. 2.0, 3.0...',
      messagePlaceholder: 'Describe in more detail what you are looking for, special requirements, preferred orientation, floor, etc...',
      sendVia: 'Choose sending method:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'Email',
      required: '* Required fields',
      whyUs: 'Why Nekretnine Stepenik?',
      completedDeals: 'Completed Deals',
      legalSupport: 'Legal Support',
      clientSupport: 'Client Support',
    },
    selling: {
      title: 'Selling Property',
      subtitle: 'Describe your property to us and we will sell it quickly at the best price',
      personalInfo: 'Your Information',
      name: 'Full Name',
      phone: 'Phone',
      email: 'Email',
      namePlaceholder: 'Your name',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'your.email@example.com',
      propertyDetails: 'Property Details',
      propertyType: 'Property Type',
      location: 'Location',
      squareMeters: 'Area (m²)',
      floor: 'Floor',
      rooms: 'Number of Rooms',
      price: 'Price',
      additionalInfo: 'Additional Information',
      selectType: 'Select type',
      apartment: 'Apartment',
      house: 'House',
      commercial: 'Commercial property',
      land: 'Land',
      garage: 'Garage',
      locationPlaceholder: 'E.g. New Belgrade, Vračar...',
      squareMetersPlaceholder: 'E.g. 65 m²',
      floorPlaceholder: 'E.g. 3/5',
      roomsPlaceholder: 'E.g. 2.0, 3.0...',
      pricePlaceholder: 'E.g. €120,000',
      messagePlaceholder: 'Describe the condition of the property, additional amenities, renovations, parking, terrace, etc...',
      sendVia: 'Choose sending method:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'Email',
      required: '* Required fields',
      advantages: 'Advantages of Selling Through Us',
      fastSale: 'Fast',
      fastSaleText: 'Sale',
      bestPrice: 'Best',
      bestPriceText: 'Price',
      legalSafety: 'Legal',
      legalSafetyText: 'Safety',
    },
    featured: {
      title: 'Featured Listings',
      viewAll: 'View All',
      subtitle: 'Check out our best currently available properties for sale and rent',
    },
    card: {
      forSale: 'For Sale',
      forRent: 'For Rent',
      month: 'per month',
    },
    stats: {
      title: 'Our Results',
      completed: 'Completed Deals',
      since: 'Operating Since',
      support: '24/7 Support',
      team: 'Legal Team',
    },
    filters: {
      location: 'Location',
      allLocations: 'All Locations',
      priceRange: 'Price',
      allPrices: 'All Prices',
      area: 'Area',
      allAreas: 'All Areas',
      type: 'Type',
      allTypes: 'All Types',
      sale: 'For Sale',
      rent: 'For Rent',
      search: 'Search',
    },
    listing: {
      perMonth: 'per month',
      bedrooms: 'Bedrooms',
      bathrooms: 'Bathrooms',
      area: 'Area',
      floor: 'Floor',
      rooms: 'Rooms',
      heating: 'Heating',
      parking: 'Parking',
      renovated: 'Renovated',
      orientation: 'Orientation',
      furniture: 'Furniture',
      distanceToRiver: 'Distance to River',
      description: 'About this property',
      features: 'Features',
      location: 'Location',
      details: 'Details',
      schedule: 'Schedule Viewing',
      contact: 'Contact Us',
      viewDetails: 'View Details',
      notFound: 'Property not found',
      backToBrowse: 'Back to listings',
      forSale: 'For Sale',
      forRent: 'For Rent',
    },
    contact: {
      title: 'Contact Information',
      agent: 'Main Agent',
      phone: 'Phone',
      email: 'Email',
      close: 'Close',
    },
    schedule: {
      title: 'Schedule Viewing',
      subtitle: 'Choose contact method',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'Email',
      whatsappDesc: 'Contact us via WhatsApp',
      viberDesc: 'Call us via Viber',
      emailDesc: 'Send us an email',
      close: 'Close',
    },
    about: {
      title: 'About Us',
      subtitle: 'Professional real estate agency with years of experience',
      story: 'Our Story',
      storyText: 'Nekretnine Stepenik was founded in 2021 with a vision to provide premium service in real estate. We focus on building long-term relationships with our clients, providing support and expertise at every step of the buying or renting process.',
      mission: 'Our Mission',
      missionText: 'We follow our clients from start to finish in every deal, ensuring that every detail is perfectly executed. With over 150 successfully completed sales and rentals, we have built a reputation as a trusted partner in real estate.',
      team: 'Our Team',
      teamText: 'Our team consists of experienced real estate agents and legal professionals who handle all legal aspects of transactions. This combination ensures our clients receive complete and secure service.',
      whyUs: 'Why Nekretnine Stepenik?',
      experienced: 'Experienced Team',
      experiencedDesc: 'Years of experience in real estate',
      legal: 'Legal Support',
      legalDesc: 'Legal team handling legal aspects',
      support: 'Complete Support',
      supportDesc: 'We follow you from start to finish',
      trust: 'Reliability',
      trustDesc: 'Over 150 satisfied clients',
    },
    footer: {
      description: 'Professional real estate agency with years of experience in sales and rentals.',
      quickLinks: 'Quick Links',
      home: 'Home',
      browse: 'Browse',
      about: 'About',
      contact: 'Contact',
      contactInfo: 'Contact Information',
      phone: 'Phone',
      email: 'Email',
      address: 'Address',
      addressText: 'Belgrade, Serbia',
      rights: 'All rights reserved.',
      services: 'Our Services',
      buying: 'Real Estate Purchase',
      selling: 'Real Estate Sale',
      renting: 'Real Estate Rental',
      legal: 'Legal Support',
    },
  },
  ru: {
    nav: {
      home: 'Главная',
      browse: 'Предложения',
      about: 'О Нас',
      contact: 'Связаться',
      buying: 'Покупка',
      selling: 'Продажа',
      lightTheme: 'Светлая Тема',
      darkTheme: 'Темная Тема',
    },
    hero: {
      title: 'Найдите Свой Идеальный Дом',
      subtitle: 'Недвижимость не является скачком, а хорошо продуманным восхождением. Каждое решение начинается с первого шага.',
      forSale: 'Продажа',
      forRent: 'Аренда',
      viewListings: 'Смотреть объявления',
      badge: 'Агентство Недвижимости Stepenik',
      headline: 'Правильный шаг ежду',
      headlineAccent: 'предложением и решением',
      founded: 'Год Основания',
      completedDeals: 'Завершенных Сделок',
      legalSupport: 'Довольных Клиентов',
      buying: 'Покупка',
      selling: 'Продажа',
    },
    cta: {
      title: 'Найдем Ваш Идеальн��й Дом Вместе',
      subtitle: 'Свяжитесь с нами сегодня и узнайте, как мы можем помочь вам достичь ваших целей в недвижимости.',
      browse: 'Просмотреть Объявления',
      contact: 'Связаться',
      buying: 'Покупка',
      selling: 'Продажа',
    },
    buying: {
      title: 'Покупка Недвижимости',
      subtitle: 'Опишите нам, какую недвижимость вы ищете, и мы найдем идеальное решение для вас',
      personalInfo: 'Ваши Данные',
      name: 'Полное Имя',
      phone: 'Телефон',
      email: 'Email',
      namePlaceholder: 'Ваше имя',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'your.email@example.com',
      searchingFor: 'Что Вы Ищете?',
      propertyType: 'Тип Недвижимости',
      location: 'Местоположение',
      budget: 'Бюджет',
      rooms: 'Количество Комнат',
      additionalInfo: 'Дополнительная Информация',
      selectType: 'Выберите тип',
      apartment: 'Квартира',
      house: 'Дом',
      commercial: 'Коммерческая недвижимость',
      land: 'Земля',
      garage: 'Гараж',
      locationPlaceholder: 'Например, Новий Белград, Врачар...',
      budgetPlaceholder: 'Например, до €100,000',
      roomsPlaceholder: 'Например, 2.0, 3.0...',
      messagePlaceholder: 'Опишите подробнее, что вы ищете, специальные требования, предпочтительное расположение, этаж, и т.д...',
      sendVia: 'Выберите метод отправки:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'Email',
      required: '* Обязательные поля',
      whyUs: 'Почему Nekretnine Stepenik?',
      completedDeals: 'Завершенных Сделок',
      legalSupport: 'Юридическая Поддержка',
      clientSupport: 'Поддержка Клиентов',
    },
    selling: {
      title: 'Продажа Недвижимости',
      subtitle: 'Опишите вашу недвижимость нам, и мы быстро продадим ее по лучшей цене',
      personalInfo: 'Ваши Данные',
      name: 'Полное Имя',
      phone: 'Телефон',
      email: 'Email',
      namePlaceholder: 'Ваше имя',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'your.email@example.com',
      propertyDetails: 'Детали Недвижимости',
      propertyType: 'Тип Недвижимости',
      location: 'Местоположение',
      squareMeters: 'Площадь (м²)',
      floor: 'Этаж',
      rooms: 'Количество Комнат',
      price: 'Цена',
      additionalInfo: 'Дополнительная Информация',
      selectType: 'Выберите тип',
      apartment: 'Квартира',
      house: 'Дом',
      commercial: 'Коммерческая недвижимость',
      land: 'Земля',
      garage: 'Гараж',
      locationPlaceholder: 'Например, Новий Белград, Врачар...',
      squareMetersPlaceholder: 'Например, 65 м²',
      floorPlaceholder: 'Например, 3/5',
      roomsPlaceholder: 'Например, 2.0, 3.0...',
      pricePlaceholder: 'Например, €120,000',
      messagePlaceholder: 'Опишите состояние недвижимости, дополнительные удобства, ремонт, парковку, террасу, и т.д...',
      sendVia: 'Выберите метод отправки:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'Email',
      required: '* Обязательные поля',
      advantages: 'Преимущества Продажи У Нас',
      fastSale: 'Быстрая',
      fastSaleText: 'Продажа',
      bestPrice: 'Лучшая',
      bestPriceText: 'Цена',
      legalSafety: 'Юридическая',
      legalSafetyText: 'Безопасность',
    },
    featured: {
      title: 'Рекомендуемые Объявления',
      viewAll: 'Показать Все',
      subtitle: 'Посмотрите наши лучшие в данный момент доступные недвижимости для продажи и аренды',
    },
    card: {
      forSale: 'Продажа',
      forRent: 'Аренда',
      month: 'в месяц',
    },
    stats: {
      title: 'Наши Результаты',
      completed: 'Завершенных Сделок',
      since: 'Работаем С',
      support: 'Поддержка 24/7',
      team: 'Юридическая Команда',
    },
    filters: {
      location: 'Местоположение',
      allLocations: 'Все Локации',
      priceRange: 'ена',
      allPrices: 'Все Цены',
      area: 'Площадь',
      allAreas: 'Все Площади',
      type: 'Тип',
      allTypes: 'Все типы',
      sale: 'Продажа',
      rent: 'Аренда',
      search: 'Поиск',
    },
    listing: {
      perMonth: 'в месяц',
      bedrooms: 'Спальни',
      bathrooms: 'Ванные',
      area: 'Площадь',
      floor: 'Этаж',
      rooms: 'Комнаты',
      heating: 'Отопление',
      parking: 'Парковка',
      renovated: 'Отремонтирован',
      orientation: 'Ориентация',
      furniture: 'Мебель',
      distanceToRiver: 'Расстояние до реки',
      description: 'Описание',
      features: 'Характеристики',
      location: 'Местоположение',
      details: 'Детали',
      schedule: 'Запланировать Просмотр',
      contact: 'Сязаться',
      viewDetails: 'Подробнее',
      notFound: 'Недвижимость не найдена',
      backToBrowse: 'Назад к объявлениям',
      forSale: 'Продажа',
      forRent: 'Аренда',
    },
    contact: {
      title: 'Контактная Информация',
      agent: 'Главный Агент',
      phone: 'Телефон',
      email: 'Email',
      close: 'Закрыть',
    },
    schedule: {
      title: 'Запланировать Просмотр',
      subtitle: 'Выберите способ связи',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'Email',
      whatsappDesc: 'Свяжитесь с нами через WhatsApp',
      viberDesc: 'Позвоните нам через Viber',
      emailDesc: 'Отправьте нам email',
      close: 'Закрыть',
    },
    about: {
      title: 'О Нас',
      subtitle: 'Профессиональное агентство недвижимости с многолетним опытом',
      story: 'Наша История',
      storyText: 'Nekretnine Stepenik была основана в 2021 году с видением предоставления премиального сервиса в сфере недвижимости. Мы фокусируемся на построении долгосрочных отношений с нашими клиентами, предоставляя поддержку и экспертизу на каждом этапе покупки или аренды недвижимости.',
      mission: 'Наша Миссия',
      missionText: 'Мы сопровождаем наших клиентов от начала до конца каждой сделки, гарантируя идеальное выполнение каждой детали. Более 150 успешно завершенных продаж и сдач в аренду создали нам репутацию надежного партнера в сфере недвижимости.',
      team: 'Наша Команда',
      teamText: 'Наша команда состоит из опытных агентов по недвижимости и юридических специалистов, которые занимаются всеми правовыми аспектами сделок. Эта комбинация гарантирует нашим клиентам полный и безопасный сервис.',
      whyUs: 'Почему Nekretnine Stepenik?',
      experienced: 'Опытная Команда',
      experiencedDesc: 'Многолетний опыт в сфере недвижимости',
      legal: 'Юридическая Поддержка',
      legalDesc: 'Юридическая команда занимается правовыми аспектами',
      support: 'Полная Поддержка',
      supportDesc: 'Мы сопровождаем вас от начала до конца',
      trust: 'Надежность',
      trustDesc: 'Более 150 довольных клиентов',
    },
    footer: {
      description: 'Профессиональное агентство недвижимости с многолетним опытом продаж и аренды.',
      quickLinks: 'Быстрые Ссылки',
      home: 'Главная',
      browse: 'Предложения',
      about: 'О Нас',
      contact: 'Контакт',
      contactInfo: 'Контактная Информация',
      phone: 'Телефон',
      email: 'Email',
      address: 'Адрес',
      addressText: 'Белград, Сербия',
      rights: 'Все права защищены.',
      services: 'Наши Услуги',
      buying: 'Покупка Недвижимости',
      selling: 'Продажа Недвижимости',
      renting: 'Аренда Недвижимости',
      legal: 'Юридическая Поддержка',
    },
  },
  tr: {
    nav: {
      home: 'Ana Sayfa',
      browse: 'İlanlar',
      about: 'Hakkımızda',
      contact: 'İletişim',
      buying: 'Satın Alma',
      selling: 'Satış',
      lightTheme: 'Açık Tema',
      darkTheme: 'Koyu Tema',
    },
    hero: {
      title: 'Mükemmel Evinizi Bulun',
      subtitle: 'Gayrimenkul, atlamadan, iyi düşünülmüş bir yükseltmedir. Her karar ilk adım ile başlar.',
      forSale: 'Satılık',
      forRent: 'Kiralık',
      viewListings: 'İlanları görüntüle',
      badge: 'Stepenik Gayrimenkul Ajansı',
      headline: 'Teklif ve karar arasında',
      headlineAccent: 'doğru adım',
      founded: 'Kuruluş Yılı',
      completedDeals: 'Tamamlanan İşlemler',
      legalSupport: 'Memnun Müşteri',
      buying: 'Satın Alma',
      selling: 'Satış',
    },
    cta: {
      title: 'Mükemmel Evimizi Birlikte Bulalım',
      subtitle: 'Bize bugün ulaşın ve gayrimenkul hedeflerinizi nasıl gerçekleştirebileceğimizi keşfedin.',
      browse: 'İlanları Göster',
      contact: 'İletişime Geç',
      buying: 'Satın Alma',
      selling: 'Satış',
    },
    buying: {
      title: 'Gayrimenkul Satın Alma',
      subtitle: 'Bize aradığınız gayrimenkulü tanımlayın ve size mükemmel bir çözüm bulacağız',
      personalInfo: 'Kişisel Bilgileriniz',
      name: 'Ad Soyad',
      phone: 'Telefon',
      email: 'E-posta',
      namePlaceholder: 'Adınız',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'your.email@example.com',
      searchingFor: 'Ne Arıyorsunuz?',
      propertyType: 'Gayrimenkul Türü',
      location: 'Konum',
      budget: 'Bütçe',
      rooms: 'Oda Sayısı',
      additionalInfo: 'Ek Bilgiler',
      selectType: 'Tür Seçin',
      apartment: 'Daire',
      house: 'Ev',
      commercial: 'Ticari Gayrimenkul',
      land: 'Zemin',
      garage: 'Garaj',
      locationPlaceholder: 'Örneğin, Novi Beograd, Vračar...',
      budgetPlaceholder: 'Örneğin, €100,000\'den az',
      roomsPlaceholder: 'Örneğin, 2.0, 3.0...',
      messagePlaceholder: 'Araştırmanızı daha detaylı tanımlayın, özel gereksinimler, tercih edilen yönlendirme, kat, vb...',
      sendVia: 'Gönderim yöntemini seçin:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'E-posta',
      required: '* Zorunlu Alanlar',
      whyUs: 'Neden Nekretnine Stepenik?',
      completedDeals: 'Tamamlanan İşlemler',
      legalSupport: 'Yasal Destek',
      clientSupport: 'Müşteri Desteği',
    },
    selling: {
      title: 'Gayrimenkul Satış',
      subtitle: 'Gayrimenkulünüzü bize tanımlayın ve en iyi fiyatta hızlıca satabiliriz',
      personalInfo: 'Kişisel Bilgileriniz',
      name: 'Ad Soyad',
      phone: 'Telefon',
      email: 'E-posta',
      namePlaceholder: 'Adınız',
      phonePlaceholder: '+381 62 123 456',
      emailPlaceholder: 'your.email@example.com',
      propertyDetails: 'Gayrimenkul Detayları',
      propertyType: 'Gayrimenkul Türü',
      location: 'Konum',
      squareMeters: 'Alan (m²)',
      floor: 'Kat',
      rooms: 'Oda Sayısı',
      price: 'Fiyat',
      additionalInfo: 'Ek Bilgiler',
      selectType: 'Tür Seçin',
      apartment: 'Daire',
      house: 'Ev',
      commercial: 'Ticari Gayrimenkul',
      land: 'Zemin',
      garage: 'Garaj',
      locationPlaceholder: 'Örneğin, Novi Beograd, Vračar...',
      squareMetersPlaceholder: 'Örneğin, 65 m²',
      floorPlaceholder: 'Örneğin, 3/5',
      roomsPlaceholder: 'Örneğin, 2.0, 3.0...',
      pricePlaceholder: 'Örneğin, €120,000',
      messagePlaceholder: 'Gayrimenkulünüzün durumunu, ek özelliklerini, yenilemelerini, park yerini, terasını, vb tanımlayın...',
      sendVia: 'Gönderim yöntemini seçin:',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      emailButton: 'E-posta',
      required: '* Zorunlu Alanlar',
      advantages: 'Bize Satış Yapanın Avantajları',
      fastSale: 'Hızlı',
      fastSaleText: 'Satış',
      bestPrice: 'En İyi',
      bestPriceText: 'Fiyat',
      legalSafety: 'Yasal',
      legalSafetyText: 'Güvenlik',
    },
    featured: {
      title: 'Öne Çıkan İlanlar',
      viewAll: 'Tümünü Görüntüle',
      subtitle: 'Satış ve kiralık için şu anda mevcut en iyi gayrimenkulleri görün',
    },
    card: {
      forSale: 'Satılık',
      forRent: 'Kiralık',
      month: 'aylık',
    },
    stats: {
      title: 'Sonuçlarımız',
      completed: 'Tamamlanan İşlemler',
      since: 'Hizmet Başlangıcı',
      support: '7/24 Destek',
      team: 'Hukuk Ekibi',
    },
    filters: {
      location: 'Konum',
      allLocations: 'Tüm Konumlar',
      priceRange: 'Fiyat',
      allPrices: 'Tüm Fiyatlar',
      area: 'Alan',
      allAreas: 'Tüm Alanlar',
      type: 'Tip',
      allTypes: 'Tüm Tipler',
      sale: 'Satılık',
      rent: 'Kiralık',
      search: 'Ara',
    },
    listing: {
      perMonth: 'aylık',
      bedrooms: 'Yatak Odası',
      bathrooms: 'Banyo',
      area: 'Alan',
      floor: 'Kat',
      rooms: 'Odalar',
      heating: 'Isıtma',
      parking: 'Park Yeri',
      renovated: 'Yenilenmiş',
      orientation: 'Yönelim',
      furniture: 'Mobilya',
      distanceToRiver: 'Nehre Mesafe',
      description: 'Açıklama',
      features: 'Özellikler',
      location: 'Konum',
      details: 'Detaylar',
      schedule: 'Görüntüleme Planla',
      contact: 'İletişime Geç',
      viewDetails: 'Detayları Görüntüle',
      notFound: 'Gayrimenkul bulunamadı',
      backToBrowse: 'İlanlara geri dön',
      forSale: 'Satılık',
      forRent: 'Kiralık',
    },
    contact: {
      title: 'İletişim Bilgileri',
      agent: 'Ana Temsilci',
      phone: 'Telefon',
      email: 'E-posta',
      close: 'Kapat',
    },
    schedule: {
      title: 'Görüntüleme Planla',
      subtitle: 'İletişim yöntemini seçin',
      whatsapp: 'WhatsApp',
      viber: 'Viber',
      email: 'E-posta',
      whatsappDesc: 'WhatsApp üzerinden iletişime geçin',
      viberDesc: 'Viber üzerinden arayın',
      emailDesc: 'Bize e-posta gönderin',
      close: 'Kapat',
    },
    about: {
      title: 'Hakkımızda',
      subtitle: 'Yıllarca deneyime sahip profesyonel gayrimenkul ajansı',
      story: 'Hikayemiz',
      storyText: 'Nekretnine Stepenik, 2021 yılında gayrimenkul alanında premium hizmet sunma vizyonuyla kuruldu. Müşterilerimizle uzun vadeli ilişkiler kurmaya odaklanıyor, satın alma veya kiralama sürecinin her adımında destek ve uzmanlık sağlıyoruz.',
      mission: 'Misyonumuz',
      missionText: 'Her işte müşterilerimizi baştan sona takip ediyor, her detayın mükemmel şekilde yürütülmesini sağlıyoruz. 150\'den fazla başarıyla tamamlanmış satış ve kiralamayla, gayrimenkul dünyasında güvenilir bir ortak olarak itibar kazandık.',
      team: 'Ekibimiz',
      teamText: 'Ekibimiz, işlemlerin tüm yasal yönlerini ele alan deneyimli gayrimenkul acenteleri ve hukuk uzmanlarından oluşmaktadır. Bu kombinasyon, müşterilerimizin eksiksiz ve güvenli hizmet almasını sağlar.',
      whyUs: 'Neden Nekretnine Stepenik?',
      experienced: 'Deneyimli Ekip',
      experiencedDesc: 'Gayrimenkul alanında yllarca deneyim',
      legal: 'Hukuki Destek',
      legalDesc: 'Yasal konularla ilgilenen hukuk ekibi',
      support: 'Tam Destek',
      supportDesc: 'Baştan sona sizinle beraberiz',
      trust: 'Güvenilirlik',
      trustDesc: '150\'den fazla memnun müşteri',
    },
    footer: {
      description: 'Satış ve kiralamada yıllarca deneyime sahip profesyonel gayrimenkul ajansı.',
      quickLinks: 'Hızlı Bağlantılar',
      home: 'Ana Sayfa',
      browse: 'İlanlar',
      about: 'Hakkımızda',
      contact: 'İletişim',
      contactInfo: 'İletişim Bilgileri',
      phone: 'Telefon',
      email: 'E-posta',
      address: 'Adres',
      addressText: 'Belgrad, Sırbistan',
      rights: 'Tüm hakları saklıdır.',
      services: 'Hizmetlerimiz',
      buying: 'Gayrimenkul Satın Alma',
      selling: 'Gayrimenkul Satış',
      renting: 'Gayrimenkul Kiralama',
      legal: 'Hukuki Destek',
    },
  },
};